version: "3.8"

services:
  minio:
    container_name: minio-test
    hostname: minio
    image: minio/minio:${MINIO_VERSION}
    entrypoint: sh
    command: -c 'mkdir -p /data/mlflow && minio server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    networks:
      - aws_test_nw

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: mlflow-aws-postgres-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-aws-storage:/var/lib/postgresql/data
    networks:
      - aws_test_nw

  mlflow:
    container_name: mlflow-aws-test
    build:
      context: .
      dockerfile: Dockerfile
    command: "mlflow server --backend-store-uri=postgresql:// --default-artifact-root=s3://mlflow/ --host=0.0.0.0 --port=5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "5000:5000"
    networks:
      - aws_test_nw
    volumes:
      - mlflow-aws-storage:/mlflow
    depends_on:
      - minio
      - postgres

volumes:
  postgres-aws-storage:
    driver: local
  mlflow-aws-storage:
    driver: local
  minio-storage:
    driver: local

networks:
  aws_test_nw:
    driver: bridge
